### ISSUE TITLE
Support for Bloodhound-CE

### ISSUE THREAD

**Issue by PfiatDe** [c3c/ADExplorerSnapshot.py#40]
First, thanks for a wonderful piece of software. Worked like a charm :)

Do you plan on supporting Bloodhound-CE in near future, as it seems like the newer features will not go into the legacy one (ADCS...).
There is a branch for bloodhound.py to support BloodHound-CE (https://github.com/dirkjanm/BloodHound.py/tree/bloodhound-ce) but I have no idea how compatible it is with ADExplorerSnapshot.

**Comment by xAiluros** [comment]
Made a very quick attempt at updating for BloodHound CE (copying from Dirk-jan's work!):
https://github.com/xAiluros/ADExplorerSnapshot.py/tree/bloodhound-ce

It seems to work for a big part, as I see the numbers in data quality tab of BH-CE:
- Users
- Groups
- Computers
- ACLs
- Relationships

There were errors for 'AllowedToDelegate', so that is probably missing.
Also ADCS info / cert templates were missing.

**Comment by Adamkadaban** [comment]
@xAiluros thanks for the work on making things compatible!

When you used this, did you have any issues viewing the results? I recently uploaded some data that bhce says was successfully ingested and analyzed, but bhce was reporting 0 users, domains, and computers. 

Is it perhaps because of the error you mentioned in your fork? Or is this a unique issue?

**Comment by xAiluros** [comment]
> @xAiluros thanks for the work on making things compatible!
> 
> When you used this, did you have any issues viewing the results? I recently uploaded some data that bhce says was successfully ingested and analyzed, but bhce was reporting 0 users, domains, and computers.
> 
> Is it perhaps because of the error you mentioned in your fork? Or is this a unique issue?

When I used my fork users, computers, domain were definitely visible and I could visualize attack paths. 
Unfortunately I'm not sure what your issue might be

**Comment by Adamkadaban** [comment]
> Unfortunately I'm not sure what your issue might be

No worries. I was ingesting about 19 million objects (7GB snapshot file), so I'm guessing it's just something with bhce itself.

Thanks again

**Comment by JJK96** [comment]
For those also waiting for this functionality. An alternative project supports bloodhound-ce https://github.com/t94j0/adexplorersnapshot-rs, maybe that fits your usecase.

**Comment by Adamkadaban** [comment]
@JJK96 That one didn't work for me, unfortunately. BloodHound gets updated so often that it's a bit hard to keep up with the changes.

I made a fork of this repo though and got things working with v6 (most current version at the time of writing): https://github.com/adamkadaban/adexplorersnapshot.py

**Comment by c3c** [comment]
Thanks for submitting the PR: https://github.com/c3c/ADExplorerSnapshot.py/pull/49 !
I'll update the README before merging to mention support for the new BH version. If anyone else is able to test this PR with BHv6, please report back :)

**Comment by swtornio** [comment]
> Thanks for submitting the PR: #49 ! I'll update the README before merging to mention support for the new BH version. If anyone else is able to test this PR with BHv6, please report back :)

I used the forked version and had to fix a typo in adexpsnapshot/__init__.py (missing a comma on line 660), but otherwise it processed the snapshot I had and ingested to a current BHCE docker just fine.

**Comment by Adamkadaban** [comment]
@swtornio Whoops, I had that typo fixed locally but forgot to push. Should be fixed now. Thanks for reviewing!

**Comment by c3c** [comment]
That was quick, thanks, merged!
